services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./infra/mongo:/docker-entrypoint-initdb.d:ro

  usuarios:
    build:
      context: ./usuarios
      dockerfile: Dockerfile
    container_name: usuarios
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/usuarios_db
    depends_on:
      - mongo
    ports:
      - "3001:3000"

  pedidos:
    build:
      context: ./pedidos
      dockerfile: Dockerfile
    container_name: pedidos
    environment:
      - PORT=3000
      - USUARIOS_URL=http://usuarios:3000
    depends_on:
      - usuarios
    ports:
      - "3002:3000"

  pagos:
    build:
      context: ./pagos
      dockerfile: Dockerfile
    container_name: pagos
    environment:
      - PORT=3000
      - PEDIDOS_URL=http://pedidos:3000
    depends_on:
      - pedidos
    ports:
      - "3003:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - usuarios
      - pedidos
      - pagos
    ports:
      - "4200:80"

volumes:
  mongo_data:
